branch-defaults:
  master:
    environment: djangotestproject-env
global:
  application_name: djangotestproject
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.03 v1.4.3 running Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
